# Generated by Django 4.2.13 on 2024-05-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('holiday_date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('days_lte', models.PositiveIntegerField()),
                ('days_gt', models.PositiveIntegerField()),
                ('days_lte_reinvest', models.PositiveIntegerField()),
                ('days_gt_reinvest', models.PositiveIntegerField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
